### ISSUE TITLE
when I run the example, i got a NullPointerException

### ISSUE THREAD

**Issue by carlye** [ToToTec/CmdOption#12]
I used jdk1.6/ jdk1.7 ,CmdOption 0.3.3/CmdOption 0.3.2 , when I run the example , I got a exception!
Exception in thread "main" java.lang.NullPointerException
	at de.tototec.cmdoption.CmdlineParser.scanOptions(CmdlineParser.java:670)
	at de.tototec.cmdoption.CmdlineParser.addObject(CmdlineParser.java:516)
	at de.tototec.cmdoption.CmdlineParser.<init>(CmdlineParser.java:109)
	at SendMail.main(SendMail.java:29)

this is my code:
import de.tototec.cmdoption.CmdOption;
import de.tototec.cmdoption.CmdlineParser;
import de.tototec.cmdoption.CmdlineParserException;

import java.util.LinkedHashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;

/**
 * Created by 春 on 2015/1/16.
 */
public class SendMail {
    public static class Config {
        @CmdOption(names = {"--help", "-h"}, description = "Show this help.", isHelp = true)
        public boolean help;

        @CmdOption(names = {"--verbose", "-v"}, description = "Be more verbose.")
        private boolean verbose;

        @CmdOption(names = {"--options", "-o"}, args = {"name", "value"}, maxCount = -1, description = "Additional options when processing names.")
        private final Map<String, String> options = new LinkedHashMap<String, String>();

        @CmdOption(args = {"file"}, description = "Names to process.", minCount = 1, maxCount = -1)
        private final List<String> names = new LinkedList<String>();
    }
    public static void main(String[] args){
        Config config = new Config();
        CmdlineParser cp = new CmdlineParser(config);
        cp.setResourceBundle(SendMail.class.getPackage().getName() + ".Messages", SendMail.class.getClassLoader());
        cp.setProgramName("myprogram");
        cp.setAboutLine("Example names processor v1.0");

        try {
            cp.parse(args);
        } catch (CmdlineParserException e) {
            System.err.println("Error: " + e.getLocalizedMessage() + "\nRun myprogram --help for help.");
            System.exit(1);
        }

        if (config.help) {
            cp.usage();
            System.exit(0);
        }

    }
}

Could you help me?Please !  my English is not very well.I am sorry

**Comment by tlahn** [comment]
Hi carlye,

thank you for reporting this. It looks like there is a bug in CmdlineParser that throws a NullPointerException when the config class has no package. We will fix this.

As a workaround / fast solution for you, just move the "SendMail" class into a package. It should work then.

**Comment by carlye** [comment]
Yes! It works!. Thank you for your help.It's very useful!

**Comment by lefou** [comment]
Fixed

**Comment by carlye** [comment]
Thanks a lot! I think CmdOption is much better than Apache's Commons CLI.It's awesome.
